name: Publish Documentation
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
      - name: Set up Python 3.10 s v
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Docs Publishing Packages
        run: pip install --upgrade -r ./.github/reqs/docs-requirements.txt

      - name: Set Git user
        run: git config user.name ${{ secrets.CI_USER }}

      - name: Set Git email
        run: git config user.email ${{ secrets.CI_EMAIL }}

      - name: Get Latest
        run: git pull

      - name: Build the Docs site
        run: mkdocs gh-deploy
